// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: proto/vad.proto

package vadpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VADEvent_EventType int32

const (
	VADEvent_SPEECH_START VADEvent_EventType = 0
	VADEvent_SPEECH_END   VADEvent_EventType = 1
)

// Enum value maps for VADEvent_EventType.
var (
	VADEvent_EventType_name = map[int32]string{
		0: "SPEECH_START",
		1: "SPEECH_END",
	}
	VADEvent_EventType_value = map[string]int32{
		"SPEECH_START": 0,
		"SPEECH_END":   1,
	}
)

func (x VADEvent_EventType) Enum() *VADEvent_EventType {
	p := new(VADEvent_EventType)
	*p = x
	return p
}

func (x VADEvent_EventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VADEvent_EventType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_vad_proto_enumTypes[0].Descriptor()
}

func (VADEvent_EventType) Type() protoreflect.EnumType {
	return &file_proto_vad_proto_enumTypes[0]
}

func (x VADEvent_EventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VADEvent_EventType.Descriptor instead.
func (VADEvent_EventType) EnumDescriptor() ([]byte, []int) {
	return file_proto_vad_proto_rawDescGZIP(), []int{1, 0}
}

type AudioChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PcmData       []byte                 `protobuf:"bytes,1,opt,name=pcm_data,json=pcmData,proto3" json:"pcm_data,omitempty"`
	SampleRate    int32                  `protobuf:"varint,2,opt,name=sample_rate,json=sampleRate,proto3" json:"sample_rate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AudioChunk) Reset() {
	*x = AudioChunk{}
	mi := &file_proto_vad_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AudioChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudioChunk) ProtoMessage() {}

func (x *AudioChunk) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vad_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudioChunk.ProtoReflect.Descriptor instead.
func (*AudioChunk) Descriptor() ([]byte, []int) {
	return file_proto_vad_proto_rawDescGZIP(), []int{0}
}

func (x *AudioChunk) GetPcmData() []byte {
	if x != nil {
		return x.PcmData
	}
	return nil
}

func (x *AudioChunk) GetSampleRate() int32 {
	if x != nil {
		return x.SampleRate
	}
	return 0
}

type VADEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          VADEvent_EventType     `protobuf:"varint,1,opt,name=type,proto3,enum=vad.VADEvent_EventType" json:"type,omitempty"`
	AudioData     []byte                 `protobuf:"bytes,2,opt,name=audio_data,json=audioData,proto3" json:"audio_data,omitempty"` // 仅 SPEECH_END 时有值，完整句子 PCM
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VADEvent) Reset() {
	*x = VADEvent{}
	mi := &file_proto_vad_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VADEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VADEvent) ProtoMessage() {}

func (x *VADEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vad_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VADEvent.ProtoReflect.Descriptor instead.
func (*VADEvent) Descriptor() ([]byte, []int) {
	return file_proto_vad_proto_rawDescGZIP(), []int{1}
}

func (x *VADEvent) GetType() VADEvent_EventType {
	if x != nil {
		return x.Type
	}
	return VADEvent_SPEECH_START
}

func (x *VADEvent) GetAudioData() []byte {
	if x != nil {
		return x.AudioData
	}
	return nil
}

var File_proto_vad_proto protoreflect.FileDescriptor

const file_proto_vad_proto_rawDesc = "" +
	"\n" +
	"\x0fproto/vad.proto\x12\x03vad\"H\n" +
	"\n" +
	"AudioChunk\x12\x19\n" +
	"\bpcm_data\x18\x01 \x01(\fR\apcmData\x12\x1f\n" +
	"\vsample_rate\x18\x02 \x01(\x05R\n" +
	"sampleRate\"\x85\x01\n" +
	"\bVADEvent\x12+\n" +
	"\x04type\x18\x01 \x01(\x0e2\x17.vad.VADEvent.EventTypeR\x04type\x12\x1d\n" +
	"\n" +
	"audio_data\x18\x02 \x01(\fR\taudioData\"-\n" +
	"\tEventType\x12\x10\n" +
	"\fSPEECH_START\x10\x00\x12\x0e\n" +
	"\n" +
	"SPEECH_END\x10\x012@\n" +
	"\n" +
	"VADService\x122\n" +
	"\fStreamingVAD\x12\x0f.vad.AudioChunk\x1a\r.vad.VADEvent(\x010\x01B#Z!internal/infrastructure/vad/vadpbb\x06proto3"

var (
	file_proto_vad_proto_rawDescOnce sync.Once
	file_proto_vad_proto_rawDescData []byte
)

func file_proto_vad_proto_rawDescGZIP() []byte {
	file_proto_vad_proto_rawDescOnce.Do(func() {
		file_proto_vad_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_vad_proto_rawDesc), len(file_proto_vad_proto_rawDesc)))
	})
	return file_proto_vad_proto_rawDescData
}

var file_proto_vad_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_vad_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_vad_proto_goTypes = []any{
	(VADEvent_EventType)(0), // 0: vad.VADEvent.EventType
	(*AudioChunk)(nil),      // 1: vad.AudioChunk
	(*VADEvent)(nil),        // 2: vad.VADEvent
}
var file_proto_vad_proto_depIdxs = []int32{
	0, // 0: vad.VADEvent.type:type_name -> vad.VADEvent.EventType
	1, // 1: vad.VADService.StreamingVAD:input_type -> vad.AudioChunk
	2, // 2: vad.VADService.StreamingVAD:output_type -> vad.VADEvent
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_vad_proto_init() }
func file_proto_vad_proto_init() {
	if File_proto_vad_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_vad_proto_rawDesc), len(file_proto_vad_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_vad_proto_goTypes,
		DependencyIndexes: file_proto_vad_proto_depIdxs,
		EnumInfos:         file_proto_vad_proto_enumTypes,
		MessageInfos:      file_proto_vad_proto_msgTypes,
	}.Build()
	File_proto_vad_proto = out.File
	file_proto_vad_proto_goTypes = nil
	file_proto_vad_proto_depIdxs = nil
}
