// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.31.1
// source: proto/vad.proto

package vadpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	VADService_StreamingVAD_FullMethodName = "/vad.VADService/StreamingVAD"
)

// VADServiceClient is the client API for VADService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VADServiceClient interface {
	StreamingVAD(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AudioChunk, VADEvent], error)
}

type vADServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewVADServiceClient(cc grpc.ClientConnInterface) VADServiceClient {
	return &vADServiceClient{cc}
}

func (c *vADServiceClient) StreamingVAD(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AudioChunk, VADEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &VADService_ServiceDesc.Streams[0], VADService_StreamingVAD_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AudioChunk, VADEvent]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type VADService_StreamingVADClient = grpc.BidiStreamingClient[AudioChunk, VADEvent]

// VADServiceServer is the server API for VADService service.
// All implementations must embed UnimplementedVADServiceServer
// for forward compatibility.
type VADServiceServer interface {
	StreamingVAD(grpc.BidiStreamingServer[AudioChunk, VADEvent]) error
	mustEmbedUnimplementedVADServiceServer()
}

// UnimplementedVADServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedVADServiceServer struct{}

func (UnimplementedVADServiceServer) StreamingVAD(grpc.BidiStreamingServer[AudioChunk, VADEvent]) error {
	return status.Error(codes.Unimplemented, "method StreamingVAD not implemented")
}
func (UnimplementedVADServiceServer) mustEmbedUnimplementedVADServiceServer() {}
func (UnimplementedVADServiceServer) testEmbeddedByValue()                    {}

// UnsafeVADServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VADServiceServer will
// result in compilation errors.
type UnsafeVADServiceServer interface {
	mustEmbedUnimplementedVADServiceServer()
}

func RegisterVADServiceServer(s grpc.ServiceRegistrar, srv VADServiceServer) {
	// If the following call panics, it indicates UnimplementedVADServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&VADService_ServiceDesc, srv)
}

func _VADService_StreamingVAD_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(VADServiceServer).StreamingVAD(&grpc.GenericServerStream[AudioChunk, VADEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type VADService_StreamingVADServer = grpc.BidiStreamingServer[AudioChunk, VADEvent]

// VADService_ServiceDesc is the grpc.ServiceDesc for VADService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VADService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "vad.VADService",
	HandlerType: (*VADServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamingVAD",
			Handler:       _VADService_StreamingVAD_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/vad.proto",
}
