# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: vad.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'vad.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tvad.proto\x12\x03vad\"3\n\nAudioChunk\x12\x10\n\x08pcm_data\x18\x01 \x01(\x0c\x12\x13\n\x0bsample_rate\x18\x02 \x01(\x05\"t\n\x08VADEvent\x12%\n\x04type\x18\x01 \x01(\x0e\x32\x17.vad.VADEvent.EventType\x12\x12\n\naudio_data\x18\x02 \x01(\x0c\"-\n\tEventType\x12\x10\n\x0cSPEECH_START\x10\x00\x12\x0e\n\nSPEECH_END\x10\x01\x32@\n\nVADService\x12\x32\n\x0cStreamingVAD\x12\x0f.vad.AudioChunk\x1a\r.vad.VADEvent(\x01\x30\x01\x42#Z!internal/infrastructure/vad/vadpbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'vad_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z!internal/infrastructure/vad/vadpb'
  _globals['_AUDIOCHUNK']._serialized_start=18
  _globals['_AUDIOCHUNK']._serialized_end=69
  _globals['_VADEVENT']._serialized_start=71
  _globals['_VADEVENT']._serialized_end=187
  _globals['_VADEVENT_EVENTTYPE']._serialized_start=142
  _globals['_VADEVENT_EVENTTYPE']._serialized_end=187
  _globals['_VADSERVICE']._serialized_start=189
  _globals['_VADSERVICE']._serialized_end=253
# @@protoc_insertion_point(module_scope)
